import http from './http'

export const getMemberStats   = () => http.get('/members/stats')
export const getMembers       = (params) => http.get('/members', { params })
export const getMember        = (id) => http.get(`/members/${id}`)
export const adjustPoints     = (id, data) => http.patch(`/members/${id}/points`, data)
export const setMemberStatus  = (id, data) => http.patch(`/members/${id}/status`, data)
export const deleteMember     = (id) => http.delete(`/members/${id}`)
export const getMemberOrders  = (id, params) => http.get(`/members/${id}/orders`, { params })
export const getPointsLogs    = (id, params) => http.get(`/members/${id}/points-logs`, { params })
export const getPointsStats   = () => http.get('/members/points-stats')
export const getAllPointsLogs  = (params) => http.get('/members/points-logs', { params })
export const getWalletStats    = () => http.get('/members/wallet-stats')
export const getAllWalletLogs  = (params) => http.get('/members/wallet-logs', { params })
export const adjustWallet      = (id, data) => http.patch(`/members/${id}/wallet`, data)
export const getMemberWalletLogs = (id, params) => http.get(`/members/${id}/wallet-logs`, { params })
export const getLevels         = () => http.get('/members/levels')
export const createLevel       = (data) => http.post('/members/levels', data)
export const updateLevel       = (id, data) => http.put(`/members/levels/${id}`, data)
export const deleteLevel       = (id) => http.delete(`/members/levels/${id}`)
export const adjustLevel       = (id, data) => http.patch(`/members/${id}/level`, data)
export const getLevelLogs      = (id, params) => http.get(`/members/${id}/level-logs`, { params })
